### PR TITLE
Fix: add missing type params to with methods

### LINKED ISSUE #15: with methods don't set type params
```scala
@data class Bar[T](n: Int, s: String)
val barI: Bar[Int] = Bar[Int](2, "a")
barI.withN(3) // Bar[Nothing]
```

### PR DESCRIPTION
**Pull request by regadas**
Hi @alexarchambault wdyt?

Fixes #15

### CODE REVIEW

**Comment by alexarchambault** [comment]
I had run into that too. IIRC, the reason I didn't fix it this way is because this prevents one to update the type parameter in some cases, like
```scala
@data class Foo[T](t: T, n: Int)
val foo = Foo("a", 2) // Foo[String]
val foo0 = foo.withT(false) // Foo[Boolean]
```
(I didn't test that, but I think this work currently).

Setting explictly the type parameters in the `with`* methods would break that, I think.

It might be possible to detect if any field type references any of the type parameters though. If none do, we could assume the type parameters aren't supposed to change, and set them explicitly like currently done in this PR.

And if any field references a type parameter, don't pass them explicitly, like done currently in case-app. (If there are several type params, there's still a possibility that only one of them is referenced and the others aren't, and these would become `Nothing` then though…)

**Comment by regadas** [comment]
Hi @alexarchambault ah yup! you are right that case doesn't work. It's a totally valid case that i didn't consider. I'll keep digging right now i'm forced to cast things and it's a bit meh.

**Comment by regadas** [comment]
Hi @alexarchambault I took a look at this and found out the following:

* The above example doesn't work as well in `master`, 

With the changes proposed `with*` methods look like:

```scala
def withT(t: T) = new Foo[T](t = t, n = this.n)
```

I think it's ok to have these changes since at least now we return `Foo[T]` instead of `Foo[Nothing]`.


* As you said to be able to allow this:

```scala
@data class Foo[T](t: T, n: Int)
val foo = Foo("a", 2) // Foo[String]
val foo0 = foo.withT(false) // Foo[Boolean]
```

we would need to define `with*` as:

```scala
def withT[T](t: T) = new Foo[T](t = t, n = this.n)
```

I actually made an experiment where this is possible, however there's one case where this get's funky and we loose coherence.

```scala
class TC[T]
object TC {
  implicit val int = new TC[Int]
  implicit val string = new TC[String]
}

@data class Bar[T](t: T)(implicit f: TC[T])
```

This examples generates:
```scala
def withT(t: T) = new Foo[T](t = t)(f = this.f)
def withF(f: TC[T]) = new Foo[T](t = this.t)(f = f)
```
Now if we want to add type params things don't work as expected `withT` needs to become smth like the following to be able to return a new `Bar[T]`

```scala
def withT[T](t: T)(implicit f: TC[T]) = new Bar[T](t = t)(f = f)
```

This is very similar to the `copy` and allows now return `Foo[T]` with new `t` and `f`. This is where i say it looses coherence, because `withT` is supposed to return a new `Foo[T]` with the new `t` value.

**Comment by alexarchambault** [comment]
Oh, I should have tested that code snippet… (I had run into other issues in Ammonite, so I gave up at the time.)

Sorry about this, let's merge this then. This is better than what is currently done in data-class, and this shouldn't break binary compatibility of the generated code.

Thanks for having pushed for it!

**Comment by regadas** [comment]
@alexarchambault no worries! 😄 Thanks!

**Pull request merged**
